-- HUAWEI商家点击统计表HUAWEI_TOTAL_CLICK
CREATE TABLE HUAWEI_SERVICE_NUMBER (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `SERVICE_NAME` varchar(128) NOT NULL DEFAULT '' COMMENT '服务号名称',
  `INDUSTRY` varchar(128) NOT NULL DEFAULT '' COMMENT '行业',
  `MERCHANT_NAME` varchar(128) NOT NULL DEFAULT '' COMMENT '商家昵称',
  `LOCATED_FIELD` varchar(128) NOT NULL DEFAULT '' COMMENT '所属域',
  `OPEN_SERVICE_NUM` bigint(20) NOT NULL DEFAULT '0' COMMENT '总开通服务号数',
  `OPEN_MENU_NUM` bigint(20) NOT NULL DEFAULT '0' COMMENT '总开通了菜单的服务号数',
  `OPEN_PAGE_NUM` bigint(20) NOT NULL DEFAULT '0' COMMENT '总开通了主页的服务号数',
  `PAGE_DAY_PV` bigint(20) NOT NULL DEFAULT '0' COMMENT '服务号主页日PV',
  `PAGE_DAY_UV` bigint(20) NOT NULL DEFAULT '0' COMMENT '服务号主页日UV',
  `PAGE_QUICK_APP_PV` bigint(20) NOT NULL DEFAULT '0' COMMENT '服务号主页快应用PV',
  `PAGE_QUICK_APP_UV` bigint(20) NOT NULL DEFAULT '0' COMMENT '服务号主页快应用UV',
  `CHAT_PV` bigint(20) NOT NULL DEFAULT '0' COMMENT '服务号会话PV',
  `CHAT_UV` bigint(20) NOT NULL DEFAULT '0' COMMENT '服务号会话UV',
  `DATA_TIME` int(11) NOT NULL DEFAULT '19700101' COMMENT '日期',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_MERCHANT_DATE` (`MERCHANT_NAME`,`DATA_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- HUAWEI商家统计表HUAWEI_SERVICE_NUMBER
CREATE TABLE `HUAWEI_TOTAL_CLICK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `INDUSTRY` varchar(128) NOT NULL DEFAULT '' COMMENT '行业',
  `MERCHANT_NAME` varchar(128) NOT NULL DEFAULT '' COMMENT '商家昵称',
  `LOCATED_FIELD` varchar(128) NOT NULL DEFAULT '' COMMENT '所在域',
  `TOTAL_CLICK` bigint(20) NOT NULL DEFAULT '0' COMMENT '总点击数',
  `DATA_TIME` int(11) NOT NULL DEFAULT '19700101' COMMENT '日期',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_MERCHANT_DATE` (`MERCHANT_NAME`,`DATA_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- XIAOMI服务号菜单统计表XIAOMI_SERVICE_MENU
CREATE TABLE `XIAOMI_SERVICE_BTN` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `SERVICE_NAME` varchar(128) NOT NULL DEFAULT '' COMMENT '服务号名称',
  `BTN_EXPO` bigint(20) NOT NULL DEFAULT '0' COMMENT '按钮曝光数',
  `BTN_CLICK` bigint(20) NOT NULL DEFAULT '0' COMMENT '按钮点击数',
  `BTN_DOWNLOAD` bigint(20) NOT NULL DEFAULT '0' COMMENT '按钮-APP下载量',
  `BTN_CLICK_RATE` decimal(9,4) NOT NULL DEFAULT '0.0000' COMMENT '按钮点击率百分比',
  `DATA_TIME` int(11) NOT NULL DEFAULT '19700101' COMMENT '日期',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_SERVICE_DATE` (`SERVICE_NAME`,`DATA_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- XIAOMI服务号按钮统计表XIAOMI_SERVICE_BTN
CREATE TABLE `XIAOMI_SERVICE_MENU` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `SERVICE_NAME` varchar(128) NOT NULL DEFAULT '' COMMENT '服务号名称',
  `MENU_EXPO` bigint(20) NOT NULL DEFAULT '0' COMMENT '菜单曝光数',
  `MENU_CLICK` bigint(20) NOT NULL DEFAULT '0' COMMENT '菜单点击数',
  `MENU_DOWNLOAD` bigint(20) NOT NULL DEFAULT '0' COMMENT '菜单-APP下载量',
  `MENU_CLICK_RATE` decimal(9,4) NOT NULL DEFAULT '0.0000' COMMENT '菜单点击率百分比',
  `DATA_TIME` int(11) NOT NULL DEFAULT '19700101' COMMENT '日期',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_SERVICE_DATE` (`SERVICE_NAME`,`DATA_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

